// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JewelryProduct.Data.Models;

public partial class Request
{
    public int Id { get; set; }

    public int? CusId { get; set; }

    public string TotalPrice { get; set; }

    public virtual Customer Cus { get; set; }

    public virtual ICollection<RequestDetail> RequestDetails { get; set; } = new List<RequestDetail>();
}